name: Statwake Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |            
            Statwake_v1.0.zip 
